# Generated by Django 5.2.17 on 2026-09-06 00:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_immutable_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=500)),
                ('source_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta')], max_length=12)),
                ('reference', models.CharField(max_length=160)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='cashclosureitem',
            name='one_cash_entry',
        ),
        migrations.AddField(
            model_name='creditmemo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditmemo',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_memos', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='credit_memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.creditmemo'),
        ),
        migrations.AddField(
            model_name='cashclosureitem',
            name='refund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closure_item', to='billing.refund'),
        ),
        migrations.AddConstraint(
            model_name='cashclosureitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment__isnull', False), ('refund__isnull', True), ('reversal__isnull', True)), models.Q(('payment__isnull', True), ('refund__isnull', True), ('reversal__isnull', False)), models.Q(('payment__isnull', True), ('refund__isnull', False), ('reversal__isnull', True)), _connector='OR'), name='one_cash_entry'),
        ),
        migrations.AddConstraint(
            model_name='creditmemo',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='credit_memo_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_positive'),
        ),
    ]
