# Generated by Django 5.2.17 on 2026-09-06 00:22

import compliance.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARCORequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Acceso'), ('rectification', 'Rectificación'), ('cancellation', 'Cancelación de datos'), ('opposition', 'Oposición')], max_length=20)),
                ('description', models.TextField()),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('identity_evidence', models.TextField(blank=True, help_text='Referencia a la verificación, no una copia de identificación.')),
                ('status', models.CharField(choices=[('pending_identity', 'Verificar identidad'), ('in_review', 'En revisión'), ('decision_sent', 'Respuesta comunicada'), ('completed', 'Atendida')], default='pending_identity', max_length=25)),
                ('response_due_on', models.DateField(blank=True, editable=False, null=True)),
                ('decision', models.TextField(blank=True)),
                ('decision_sent_on', models.DateField(blank=True, null=True)),
                ('granted', models.BooleanField(blank=True, null=True)),
                ('implementation_due_on', models.DateField(blank=True, editable=False, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('implementation_evidence', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arco_requests', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default=compliance.models.cancellation_folio, editable=False, max_length=25, unique=True)),
                ('channel', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('network_disconnect_pending', models.BooleanField(default=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='core.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contract', 'Contrato de adhesión'), ('privacy', 'Aviso de privacidad'), ('rights', 'Carta de derechos'), ('network', 'Política de gestión de red')], max_length=20)),
                ('version', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('effective_on', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado para uso')], default='draft', max_length=20)),
                ('registration_reference', models.CharField(blank=True, help_text='Registro PROFECO/RPC cuando corresponda.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['kind', '-effective_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('contract', 'Aceptación de contrato'), ('privacy_notice', 'Entrega de aviso'), ('marketing', 'Consentimiento publicitario'), ('autopay', 'Autorización de cargo recurrente'), ('document_delivery', 'Entrega de documento')], max_length=30)),
                ('channel', models.CharField(max_length=30)),
                ('evidence', models.TextField()),
                ('content_snapshot', models.TextField(editable=False)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_consents', to='core.customer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='compliance.documentversion')),
            ],
        ),
        migrations.CreateModel(
            name='LegalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('source_url', models.URLField(max_length=700)),
                ('legal_reference', models.CharField(max_length=200)),
                ('effective_on', models.DateField(blank=True, null=True)),
                ('applicable', models.BooleanField(default=True)),
                ('production_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('unreviewed', 'Sin verificar'), ('in_progress', 'En trámite'), ('approved', 'Verificado')], default='unreviewed', max_length=20)),
                ('evidence', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_requirements', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RetentionHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Usa * para todas las categorías del cliente.', max_length=100)),
                ('reason', models.TextField()),
                ('authority_reference', models.CharField(blank=True, max_length=200)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('lawful_basis', models.TextField()),
                ('retention_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('disposal_method', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=700)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ARCOExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('response', 'Respuesta'), ('implementation', 'Ejecución')], max_length=20)),
                ('reason', models.TextField()),
                ('notified_on', models.DateField()),
                ('notification_evidence', models.TextField()),
                ('previous_due_on', models.DateField()),
                ('extended_due_on', models.DateField()),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extensions', to='compliance.arcorequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('request', 'stage'), name='one_arco_extension_per_stage')],
            },
        ),
        migrations.CreateModel(
            name='BusinessHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('is_working_day', models.BooleanField(default=False, help_text='Marca si una disposición habilita esta fecha como hábil.')),
                ('source_reference', models.CharField(blank=True, max_length=300)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'date'), name='unique_organization_holiday')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('organization', 'kind', 'version'), name='unique_legal_document_version'),
        ),
        migrations.AddConstraint(
            model_name='legalrequirement',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_organization_legal_requirement'),
        ),
    ]
