# Generated by Django 5.2.17 on 2026-09-06 00:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('core', '0003_healthcheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contract_change', 'Cambio contractual: 30 días'), ('automatic_renewal', 'Renovación automática: 5 días')], max_length=24)),
                ('effective_on', models.DateField()),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('requires_consent', models.BooleanField(default=True)),
                ('renewal_amount_mxn', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('renewal_frequency', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_channel', models.CharField(blank=True, max_length=40)),
                ('delivered_on', models.DateField(blank=True, null=True)),
                ('delivery_evidence', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_evidence', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_notices_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compliance.documentversion')),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.notification')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_notices', to='core.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('support_ticket_content', 'Contenido de tickets resueltos'), ('arco_request_content', 'Contenido de solicitudes ARCO concluidas')], max_length=40)),
                ('record_ids', models.JSONField(default=list)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('external_copies_evidence', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_previews', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
