# Generated by Django 5.2.17 on 2026-09-06 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_regulatorynotice_retentiondisposal'),
        ('core', '0003_healthcheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_reference', models.CharField(max_length=200)),
                ('registered_on', models.DateField()),
                ('effective_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=700)),
                ('evidence', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict, editable=False)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='legal_registration', to='core.plan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
