# Generated by Django 5.2.17 on 2026-09-06 00:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Sucursal')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre comercial')),
                ('legal_name', models.CharField(blank=True, max_length=254, verbose_name='Razón social')),
                ('rfc', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$', 'RFC inválido.')], verbose_name='RFC')),
                ('timezone', models.CharField(default='America/Chihuahua', max_length=80, verbose_name='Zona horaria')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('demo_mode', models.BooleanField(default=True, verbose_name='Entorno de demostración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('topic', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=200)),
                ('details', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Número de cliente')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre / razón social')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Domicilio de servicio')),
                ('rfc', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$', 'RFC inválido.')], verbose_name='RFC')),
                ('fiscal_regime', models.CharField(blank=True, max_length=3, verbose_name='Régimen fiscal')),
                ('fiscal_postal_code', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Escribe cinco dígitos.')], verbose_name='Código postal fiscal')),
                ('invoice_use', models.CharField(default='S01', max_length=4, verbose_name='Uso CFDI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('source', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.outboxevent')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del plan')),
                ('download_mbps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Descarga (Mbps)')),
                ('upload_mbps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Subida (Mbps)')),
                ('price_mxn', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Mensualidad con IVA (MXN)')),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0.160'), max_digits=4, verbose_name='Tasa IVA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de instalación'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activación real')),
                ('paid_until', models.DateTimeField(blank=True, null=True, verbose_name='Pagado hasta')),
                ('access_username', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_.@-]+$', 'Usa letras, números, punto, guion, @ o _.')], verbose_name='Usuario PPPoE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='core_custom_name_b5e864_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='core_custom_phone_cf7ec3_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('price_mxn__gt', 0)), name='plan_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 1)), name='plan_tax_range'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'paid_until'], name='core_subscr_status_d08970_idx'),
        ),
    ]
