# Generated by Django 5.2.17 on 2026-09-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_immutable_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
