# Generated by Django 5.2.17 on 2026-09-06 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_healthcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentState',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('release', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuntimeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=160, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('release', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=120)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['role', 'identifier'],
            },
        ),
    ]
