# Generated by Django 5.2.17 on 2026-09-06 00:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('management_host', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IPv4 de administración')),
                ('ssh_port', models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Puerto SSH')),
                ('username', models.CharField(max_length=64, verbose_name='Usuario SSH')),
                ('password_encrypted', models.TextField(blank=True)),
                ('radius_secret_encrypted', models.TextField(blank=True)),
                ('is_lab', models.BooleanField(default=True, verbose_name='Laboratorio aislado')),
                ('candidate_host_key', models.TextField(blank=True)),
                ('trusted_host_key', models.TextField(blank=True)),
                ('trusted_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('readiness', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RadiusCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_encrypted', models.TextField()),
                ('is_lab', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_mbps', models.PositiveIntegerField(default=10)),
                ('upload_mbps', models.PositiveIntegerField(default=5)),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_credential', to='core.subscription')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.router')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisioningJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('probe', 'Leer huella SSH'), ('discover', 'Descubrir'), ('apply', 'Aplicar plan'), ('rollback', 'Revertir recursos propios'), ('verify', 'Verificar enlace'), ('lab', 'Prueba PPPoE real'), ('disconnect', 'Desconectar sesión')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('succeeded', 'Completado'), ('failed', 'Falló')], default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('journal', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='network.router')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=128)),
                ('framed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('input_octets', models.PositiveBigIntegerField(default=0)),
                ('output_octets', models.PositiveBigIntegerField(default=0)),
                ('terminate_cause', models.CharField(blank=True, max_length=100)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.router')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('router', 'session_id'), name='radius_router_session_unique')],
            },
        ),
    ]
