# Generated by Django 5.2.17 on 2026-09-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiuscredential',
            name='commissioning',
            field=models.BooleanField(default=False),
        ),
    ]
