# Generated by Django 5.2.17 on 2026-09-06 06:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_primary(apps, schema_editor):
    apps.get_model('network', 'NetworkNode').objects.using(schema_editor.connection.alias).get_or_create(pk='primary', defaults={'name': 'Servidor principal'})


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_radiussession_replayed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{0,39}$')])),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('public_endpoint', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IPv4 pública')),
                ('radius_token_digest', models.CharField(blank=True, max_length=64)),
                ('worker_token', models.UUIDField(editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(editable=False, null=True)),
                ('generation', models.PositiveBigIntegerField(default=0, editable=False)),
            ],
            options={'constraints': [models.UniqueConstraint(condition=~models.Q(radius_token_digest=''), fields=('radius_token_digest',), name='network_node_unique_token')]},
        ),
        migrations.AddField(
            model_name='provisioningjob',
            name='worker_generation',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='provisioningjob',
            name='worker_token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='execution_blocked',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(seed_primary, migrations.RunPython.noop),
        migrations.AddField(
            model_name='router',
            name='network_node',
            field=models.ForeignKey(default='primary', on_delete=django.db.models.deletion.PROTECT, related_name='routers', to='network.networknode', verbose_name='Servidor de red'),
        ),
    ]
