# Generated by Django 5.2.17 on 2026-09-06 00:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_encrypted', models.TextField(blank=True)),
                ('password_encrypted', models.TextField(blank=True)),
                ('csd_encrypted', models.TextField(blank=True)),
                ('fiel_encrypted', models.TextField(blank=True)),
                ('issuer_rfc', models.CharField(default='EKU9003173C9', max_length=13)),
                ('issuer_name', models.CharField(default='ESCUELA KEMPER URGATE', max_length=254)),
                ('fiscal_regime', models.CharField(default='601', max_length=3)),
                ('postal_code', models.CharField(default='20928', max_length=5)),
                ('environment', models.CharField(default='demo', editable=False, max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Factura'), ('payment', 'Complemento de pago')], default='income', max_length=12)),
                ('local_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitting', 'Enviando'), ('stamped', 'Timbrado'), ('error', 'Rechazado'), ('uncertain', 'Por recuperar'), ('cancel_pending', 'Cancelación pendiente'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('payment_method', models.CharField(choices=[('PUE', 'PUE'), ('PPD', 'PPD')], default='PPD', max_length=3)),
                ('payment_form', models.CharField(default='99', max_length=2)),
                ('request_xml', models.TextField(blank=True)),
                ('xml', models.TextField(blank=True)),
                ('cancellation_xml', models.TextField(blank=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=2)),
                ('cancellation_replacement', models.CharField(blank=True, max_length=36)),
                ('cancellation_code', models.CharField(blank=True, max_length=30)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('stamped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_document', to='billing.allocation')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'income')), fields=('invoice',), name='one_income_cfdi_per_invoice'), models.CheckConstraint(condition=models.Q(models.Q(('allocation__isnull', True), ('kind', 'income')), models.Q(('allocation__isnull', False), ('kind', 'payment')), _connector='OR'), name='cfdi_payment_allocation')],
            },
        ),
    ]
