# Generated by Django 5.2.17 on 2026-09-06 00:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_xml', models.TextField()),
                ('outcome', models.CharField(max_length=20)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='fiscal.fiscaldocument')),
            ],
        ),
    ]
