# Generated by Django 5.2.17 on 2026-09-06 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_creditmemo_refund_and_more'),
        ('core', '0003_healthcheck'),
        ('fiscal', '0002_fiscalattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('periodicity', models.CharField(default='04', max_length=2)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='fiscaldocument',
            name='cfdi_payment_allocation',
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='credit_memo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_document', to='billing.creditmemo'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='kind',
            field=models.CharField(choices=[('income', 'Factura'), ('payment', 'Complemento de pago'), ('credit', 'Nota de crédito'), ('global', 'Factura global')], default='income', max_length=12),
        ),
        migrations.AddField(
            model_name='globalbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='global_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document', to='fiscal.globalbatch'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocation__isnull', True), ('credit_memo__isnull', True), ('global_batch__isnull', True), ('invoice__isnull', False), ('kind', 'income')), models.Q(('allocation__isnull', False), ('credit_memo__isnull', True), ('global_batch__isnull', True), ('invoice__isnull', False), ('kind', 'payment')), models.Q(('allocation__isnull', True), ('credit_memo__isnull', False), ('global_batch__isnull', True), ('invoice__isnull', False), ('kind', 'credit')), models.Q(('allocation__isnull', True), ('credit_memo__isnull', True), ('global_batch__isnull', False), ('invoice__isnull', True), ('kind', 'global')), _connector='OR'), name='cfdi_payment_allocation'),
        ),
        migrations.AddField(
            model_name='globalitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='fiscal.globalbatch'),
        ),
        migrations.AddField(
            model_name='globalitem',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='global_item', to='billing.invoice'),
        ),
    ]
