# Generated by Django 5.2.17 on 2026-09-06 06:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_globalbatch_globalitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaldocument',
            name='pdf_content',
            field=models.BinaryField(blank=True, default=bytes),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='pdf_source_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.CreateModel(
            name='FiscalJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.CharField(max_length=128, unique=True)),
                ('operation', models.CharField(choices=[('stamp', 'Timbrado'), ('recover', 'Recuperación'), ('cancel', 'Cancelación'), ('cancellation_status', 'Consulta de cancelación'), ('verify', 'Verificación de conexión'), ('pdf', 'Preparación de PDF')], max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Pendiente'), ('running', 'En proceso'), ('succeeded', 'Completado'), ('failed', 'No completado'), ('review', 'Requiere revisión')], default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('claim_token', models.UUIDField(editable=False, null=True)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='fiscal.fiscaldocument')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='fiscal.fiscalprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='fiscal_job_dispatch')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', True), ('operation', 'verify'), ('profile__isnull', False)), models.Q(('document__isnull', False), ('profile__isnull', True), models.Q(('operation', 'verify'), _negated=True)), _connector='OR'), name='fiscal_job_target'), models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('document',), name='one_active_fiscal_document_job'), models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('profile',), name='one_active_fiscal_profile_job')],
            },
        ),
    ]
