#!/bin/sh
set -eu
# Passwords are URL-safe random strings generated by the installer.
case "$FIREISP_DB_PASSWORD" in *[!A-Za-z0-9_-]*|'') exit 1 ;; esac
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<EOSQL
CREATE ROLE fireisp LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '$FIREISP_DB_PASSWORD';
CREATE DATABASE fireisp OWNER fireisp;
REVOKE ALL ON DATABASE fireisp FROM PUBLIC;
EOSQL
