# Generated by Django 5.2.17 on 2026-09-06 00:22

import django.core.validators
import django.db.models.deletion
import operations.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency_mhz', models.PositiveIntegerField(blank=True, null=True)),
                ('channel_width_mhz', models.PositiveIntegerField(blank=True, null=True)),
                ('outdoor', models.BooleanField(default=True)),
                ('dfs_required', models.BooleanField(default=False)),
                ('dfs_enabled', models.BooleanField(default=False)),
                ('tpc_required', models.BooleanField(default=False)),
                ('tpc_enabled', models.BooleanField(default=False)),
                ('regulatory_basis', models.TextField(blank=True, help_text='Banda, clase de equipo, límite y disposición técnica vigente.')),
                ('capacity_mbps', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('cpe', 'CPE'), ('ap', 'Punto de acceso'), ('backhaul', 'Enlace de transporte'), ('router', 'Router')], default='cpe', max_length=20)),
                ('status', models.CharField(choices=[('stock', 'Almacén'), ('installed', 'Instalado'), ('repair', 'Reparación'), ('retired', 'Retirado')], default='stock', max_length=20)),
                ('homologation_certificate', models.CharField(blank=True, max_length=150)),
                ('homologation_verified', models.BooleanField(default=False)),
                ('homologation_evidence', models.TextField(blank=True)),
                ('firmware', models.CharField(blank=True, max_length=100)),
                ('regulatory_profile', models.CharField(default='Mexico', max_length=100)),
                ('tx_power_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('antenna_gain_dbi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cable_loss_db', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('allowed_eirp_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subscription')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='operations.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('structure_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('owner_permission', models.TextField(blank=True, help_text='Referencia al contrato de arrendamiento o permiso del propietario.')),
                ('permit_status', models.CharField(choices=[('unreviewed', 'Pendiente de revisión'), ('approved', 'Documentación verificada'), ('not_required', 'No aplica, con fundamento')], default='unreviewed', max_length=20)),
                ('permit_evidence', models.TextField(blank=True, help_text='Folio, autoridad, vigencia y fundamento de permisos aplicables al sitio.')),
                ('permit_expires_on', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='sector',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sectors', to='operations.site'),
        ),
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('provider_attributable', models.BooleanField(default=False)),
                ('attribution_evidence', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='outages', to='core.subscription')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.site')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('installation', 'Instalación'), ('repair', 'Reparación'), ('retrieval', 'Retiro')], default='installation', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En ejecución'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completion_evidence', models.TextField(blank=True, help_text='Identificación del equipo, pruebas realizadas, resultado y aceptación del cliente. No agregues contraseñas.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='OutageCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('proportional_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_reference', models.CharField(blank=True, max_length=150)),
                ('outage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='operations.outage')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('outage', 'subscription', 'period_start', 'period_end'), name='unique_outage_subscription_credit')],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default=operations.models.ticket_folio, editable=False, max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('technical', 'Falla técnica'), ('billing', 'Aclaración de facturación'), ('general', 'Consulta')], default='technical', max_length=16)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('channel', models.CharField(default='staff', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En atención'), ('resolved', 'Resuelto')], default='open', max_length=16)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(default=operations.models.complaint_deadline)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.customer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'kind', 'status'], name='operations__custome_a23952_idx')],
            },
        ),
    ]
